#!/usr/bin/env node
/**
 * Evocreatives Agency — Project Setup Script
 * ──────────────────────────────────────────
 * Usage: npm run setup
 *
 * This script:
 *  1. Prompts for client info
 *  2. Creates .env.local with project variables
 *  3. Installs all dependencies
 *  4. Initializes the Vercel project
 *  5. Prints the GitHub Secrets you need to add
 *  6. Creates the first git commit
 */

const { execSync } = require('child_process');
const readline = require('readline');
const fs = require('fs');
const path = require('path');

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise(res => rl.question(q, res));

const run = (cmd, opts = {}) => {
  try {
    return execSync(cmd, { stdio: opts.silent ? 'pipe' : 'inherit', ...opts }).toString().trim();
  } catch (e) {
    if (!opts.optional) throw e;
    return '';
  }
};

const colors = {
  reset: '\x1b[0m', green: '\x1b[32m', yellow: '\x1b[33m',
  cyan: '\x1b[36m', bold: '\x1b[1m', red: '\x1b[31m', dim: '\x1b[2m',
};
const c = (col, str) => `${colors[col]}${str}${colors.reset}`;

async function main() {
  console.log('\n' + c('bold', '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'));
  console.log(c('bold', '  Evocreatives Agency — Project Setup'));
  console.log(c('bold', '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━') + '\n');

  const clientName   = await ask(c('cyan', '? Client name: '));
  const clientSlug   = clientName.toLowerCase().replace(/[^a-z0-9]/g, '-');
  const clientDomain = await ask(c('cyan', `? Production domain (e.g. ${clientSlug}.com): `));
  const stack        = await ask(c('cyan', '? Stack [nextjs/vite/html] (default: nextjs): ')) || 'nextjs';
  const sentry       = await ask(c('cyan', '? Set up Sentry error tracking? [y/n] (default: y): ')) || 'y';

  console.log('\n' + c('yellow', `Setting up: ${clientName} (${clientSlug})`));

  const envContent = `# ${clientName} — Project Environment\n# Generated by Evocreatives setup script\n# DO NOT COMMIT THIS FILE\n\nNEXT_PUBLIC_SITE_NAME="${clientName}"\nNEXT_PUBLIC_SITE_URL="https://${clientDomain}"\n\n# Add API keys below:\n# DATABASE_URL=\n# NEXT_PUBLIC_GA_ID=\n# SENTRY_DSN=\n`;
  fs.writeFileSync('.env.local', envContent);
  console.log(c('green', '✓') + ' Created .env.local');

  const pkgPath = path.join(process.cwd(), 'package.json');
  if (fs.existsSync(pkgPath)) {
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
    pkg.name = clientSlug;
    pkg.description = `${clientName} website`;
    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
    console.log(c('green', '✓') + ' Updated package.json');
  }

  console.log(c('dim', '\nInstalling dependencies...'));
  run('npm install');
  run('npx playwright install chromium firefox', { optional: true });
  console.log(c('green', '✓') + ' Dependencies installed');

  const vercelInstalled = run('vercel --version', { silent: true, optional: true });
  if (!vercelInstalled) {
    console.log(c('yellow', '⚠') + '  Vercel CLI not found. Installing...');
    run('npm install -g vercel@latest');
  }

  console.log(c('dim', '\nLinking Vercel project...'));
  run('vercel link --yes', { optional: true });

  const vercelJson = path.join('.vercel', 'project.json');
  let orgId = '', projectId = '';
  if (fs.existsSync(vercelJson)) {
    const vData = JSON.parse(fs.readFileSync(vercelJson, 'utf8'));
    orgId = vData.orgId || '';
    projectId = vData.projectId || '';
    console.log(c('green', '✓') + ' Vercel project linked');
  } else {
    console.log(c('yellow', '⚠') + '  Vercel link skipped (run manually: vercel link)');
  }

  if (sentry.toLowerCase() === 'y') {
    console.log(c('dim', '\nInitializing Sentry...'));
    run('npx @sentry/wizard@latest -i nextjs --no-telemetry', { optional: true });
  }

  const gitExists = run('git rev-parse --git-dir', { silent: true, optional: true });
  if (gitExists) {
    run('git add .');
    run(`git commit -m "chore: init ${clientName} project"`, { optional: true });
    console.log(c('green', '✓') + ' Initial commit created');
  }

  console.log('\n' + c('bold', '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'));
  console.log(c('bold', '  GitHub Secrets Required'));
  console.log(c('bold', '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'));
  console.log(c('dim', 'Go to: GitHub repo → Settings → Secrets and variables → Actions\n'));

  const secrets = [
    ['VERCEL_TOKEN',      'Get from: vercel.com/account/tokens'],
    ['VERCEL_ORG_ID',     orgId || '← from .vercel/project.json'],
    ['VERCEL_PROJECT_ID', projectId || '← from .vercel/project.json'],
    ['LHCI_GITHUB_APP_TOKEN', 'Optional: from github.com/apps/lighthouse-ci'],
  ];

  secrets.forEach(([name, hint]) => {
    const val = orgId && name === 'VERCEL_ORG_ID' ? c('green', orgId) :
                projectId && name === 'VERCEL_PROJECT_ID' ? c('green', projectId) :
                c('dim', hint);
    console.log(`  ${c('yellow', name.padEnd(24))} ${val}`);
  });

  console.log('\n' + c('bold', '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'));
  console.log(c('bold', '  Next Steps'));
  console.log(c('bold', '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'));
  console.log(`
  1. Add the GitHub Secrets listed above
  2. Push to GitHub:  ${c('cyan', 'git push origin main')}
  3. GitHub Actions will: build → test → deploy
  4. Preview URL will appear in the PR comments
  5. Run stress test:  ${c('cyan', 'k6 run tests/stress/load.js')}

  ${c('green', '✓')} Project: ${c('bold', clientName)}
  ${c('green', '✓')} Domain:  ${c('bold', clientDomain)}
  ${c('green', '✓')} Stack:   ${c('bold', stack)}
`);

  rl.close();
}

main().catch(err => {
  console.error(c('red', '\nSetup failed:'), err.message);
  process.exit(1);
});
